### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by emeruvia**
Add team members to readme file

### CODE REVIEW

**Comment by emeruvia** [comment]
@DevonJerothe @Jgomez95 @jfleurent @maillouxc 
Any updates on this?

**Comment by Jgomez95** [comment]
What did you change?

**Review by DevonJerothe — APPROVED** [review]

**Comment by DevonJerothe** [comment]
Adding to my activity count :)

**Comment by maillouxc** [comment]
Bruh what happened I just 40 emails from this

**Comment by Jgomez95** [comment]
I think there’s an issue with production

**Comment by emeruvia** [comment]
@maillouxc any updates on this? Can we get the CI build fixed

**Review by maillouxc — APPROVED** [review]

**Pull request merged**
